version: '3'
services:
    app:
        container_name: app-webhook-viewer
        build: etc/infrastructure/php
        volumes:
            - .:/var/www:cached
        restart: on-failure
        tty: true
        ports:
            - "8000:8000"
        expose:
            - "9000"
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
        networks:
            - app-network
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        restart: on-failure
        links:
            - app
        volumes:
            - .:/var/www
            - ./etc/infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.220.0/28